### ISSUE TITLE
Projet vide

### ISSUE THREAD

**Issue by MamadouDjigo** [boubaonline/FirstProjectEdacy#1]
@boubaonline Ton repo est vide pour le moment. Merci d'ajouter le plus tôt possible le projet

**Comment by boubaonline** [comment]
@MamadouDjigo  Bonjour Mamadou, c'est fait j'ai rajouté le projet. Désolé pour le retard.

**Comment by MamadouDjigo** [comment]
@boubaonline C'est quoi votre nom , prénom et email?

**Comment by MamadouDjigo** [comment]
Bonjour BoubaOnline,
c’est quoi votre nom, prénom,email et numéro de téléphone?
Bien cordialement
____
Mamadou Djigo
Country Director

EDACY 
+221 77 516 05 06
Skype : +221 77 516 05 06
WhatsApp : +221 77 516 05 06

Follow us on: Facebook <http://www.facebook.com/edacyhq>, Twitter <http://www.twitter.com/edacyhq>, LinkedIn <http://linkedin.com/company/edacy>, Instagram <http://instagram.com/edacyhq>, Medium <https://medium.com/edacyblog>, <https://medium.com/edacyblog> Youtube <https://www.youtube.com/channel/UCQqwjFtcDt--3TIXChWouUw>!
www.edacy.com <http://www.edacy.com/> 

Aspire Farther

**Comment by boubaonline** [comment]
@MamadouDjigo 
Mes coordonnées:
Boubacar Coulibaly
boubadomogo@gmail.com
+221786315797
